#!/usr/bin/env node
'use strict';

/**
 * MalenHub build
 * --------------
 * 1. Scans  jeux/*.html  -> one hole per game on the hub
 * 2. Writes games.json + games.js (the manifest the hub reads)
 * 3. Copies the whole site into dist/  (Vercel outputDirectory)
 *
 * Usage:
 *   node build.js            build only
 *   node build.js --serve    build, then serve ./dist on http://localhost:5173
 */

const fs = require('fs');
const path = require('path');
const http = require('http');

const ROOT = __dirname;
const JEUX_DIR = path.join(ROOT, 'jeux');
const DIST = path.join(ROOT, 'dist');

/* Root entries that must never be published. */
const SKIP_ROOT = new Set([
  'node_modules',
  'dist',
  '.git',
  '.github',
  '.vercel',
  '.vscode',
  '.DS_Store',
  '.gitignore',
  'build.js',
  'package.json',
  'package-lock.json',
  'vercel.json',
  'README.md',
  'games.json',
  'games.js',
]);

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.htm': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
  '.ico': 'image/x-icon',
  '.glb': 'model/gltf-binary',
  '.gltf': 'model/gltf+json',
  '.mp3': 'audio/mpeg',
  '.ogg': 'audio/ogg',
  '.wav': 'audio/wav',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.txt': 'text/plain; charset=utf-8',
  '.md': 'text/markdown; charset=utf-8',
};

/* ------------------------------------------------------------------ utils */

function decodeEntities(str) {
  return str
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(+n))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&apos;/gi, "'");
}

function titleCase(str) {
  return str
    .replace(/[-_+]+/g, ' ')
    .replace(/([a-zà-ÿ])([A-ZÀ-Ý])/g, '$1 $2')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^./, (c) => c.toUpperCase());
}

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else if (entry.isFile()) fs.copyFileSync(s, d);
  }
}

function rmrf(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

/* ------------------------------------------------------------ game scan  */

/** A game is any *.html directly inside jeux/ that does not start with _ or . */
function scanGames() {
  if (!fs.existsSync(JEUX_DIR)) return [];

  const files = fs
    .readdirSync(JEUX_DIR, { withFileTypes: true })
    .filter((e) => e.isFile())
    .filter((e) => /\.html?$/i.test(e.name))
    .filter((e) => !e.name.startsWith('_') && !e.name.startsWith('.'))
    .map((e) => e.name);

  files.sort((a, b) => a.localeCompare(b, 'fr', { numeric: true, sensitivity: 'base' }));

  return files.map((file, i) => {
    let name = '';
    try {
      const html = fs.readFileSync(path.join(JEUX_DIR, file), 'utf8');
      const m = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
      if (m) name = decodeEntities(m[1]).replace(/\s+/g, ' ').trim();
    } catch {
      /* unreadable file: fall back to the filename */
    }
    if (!name || name.length > 60) name = titleCase(file.replace(/\.html?$/i, ''));
    return { id: `g${i + 1}`, index: i, name, file, url: `jeux/${file}` };
  });
}

/* ----------------------------------------------------------------- build */

function build() {
  const games = scanGames();

  fs.writeFileSync(path.join(ROOT, 'games.json'), JSON.stringify(games, null, 2) + '\n');
  fs.writeFileSync(
    path.join(ROOT, 'games.js'),
    '/* GENERATED by build.js - do not edit */\nwindow.MALEN_GAMES = ' +
      JSON.stringify(games) +
      ';\n'
  );

  rmrf(DIST);
  fs.mkdirSync(DIST, { recursive: true });

  for (const entry of fs.readdirSync(ROOT, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || SKIP_ROOT.has(entry.name)) continue;
    const s = path.join(ROOT, entry.name);
    const d = path.join(DIST, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else if (entry.isFile()) fs.copyFileSync(s, d);
  }

  /* the manifest lives at the repo root but must be published too */
  fs.copyFileSync(path.join(ROOT, 'games.json'), path.join(DIST, 'games.json'));
  fs.copyFileSync(path.join(ROOT, 'games.js'), path.join(DIST, 'games.js'));

  const lines = [
    '',
    '  MalenHub build',
    '  -------------',
    `  ${games.length} jeu${games.length === 1 ? '' : 'x'} -> ${games.length} trou${games.length === 1 ? '' : 's'}`,
  ];
  for (const g of games) lines.push(`    - ${g.name}  (jeux/${g.file})`);
  if (!games.length) lines.push('    (dossier jeux/ vide - ajoute des fichiers .html)');
  lines.push('  -> dist/');
  lines.push(`  (${games.length} manifest entry${games.length === 1 ? '' : 'ies'})`);
  lines.push('');
  console.log(lines.join('\n'));

  return games;
}

/* ----------------------------------------------------------------- serve */

function serve(port = 5173) {
  const server = http.createServer((req, res) => {
    const url = decodeURIComponent((req.url || '/').split('?')[0]);
    let file = path.join(DIST, path.normalize(url).replace(/^([\\/])+/, ''));
    if (!file.startsWith(DIST)) {
      res.writeHead(403).end('Forbidden');
      return;
    }
    if (fs.existsSync(file) && fs.statSync(file).isDirectory()) file = path.join(file, 'index.html');

    /* a missing file that looks like an asset must 404 loudly, otherwise you
       get index.html served as text/javascript and a baffling MIME error */
    if (!fs.existsSync(file)) {
      if (path.extname(file)) {
        res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' }).end('404 Not Found: ' + url);
        return;
      }
      file = path.join(DIST, 'index.html');
    }

    const body = fs.readFileSync(file);
    res.writeHead(200, {
      'Content-Type': MIME[path.extname(file).toLowerCase()] || 'application/octet-stream',
      'Cache-Control': 'no-store',
    });
    res.end(body);
  });

  server.listen(port, () => {
    console.log(`  MalenHub dev server -> http://localhost:${port}\n`);
  });
}

if (require.main === module) {
  build();
  if (process.argv.includes('--serve')) {
    const pArg = process.argv[process.argv.indexOf('--serve') + 1];
    serve(pArg && /^\d+$/.test(pArg) ? +pArg : 5173);
  }
}

module.exports = { build, scanGames };
